language: python
python:
  - "3.5"

before_install: 
  - mkdir dist
install: 
  - python3 -m pip install --user --upgrade setuptools wheel
script: 
  - python3 setup.py sdist bdist_wheel

deploy:
  provider: releases
  api_key: 
    secure: ""
  file: "dist/home_temp_sensor-0.0.1.tar.gz"
  overwrite: true

notifications:
  email: false
