language: python
python:
  - "3.5"
 

install:
  - pip3 install -r requirements.txt
  - pip3 install .

script: pytest one_home_sensor/tests.py





deploy:
  provider: pypi
  user: "__token__"
  password: "$PIPI_TOKEN_PASS" 
  on:
    tags: true

notifications:
  email: false
