language: python
python:
  - "3.5"
  - "pypy3" 


install:
  - pip3 install -r requirements.txt
  - pip3 install .

script: pytest home_temp_sensor/tests.py

deploy:
  provider: pypi
  user: "__token__"
  password: "$PIPI_TOKEN_PASS" # not the best way but ... not critical to me 

notifications:
  email: false
