language: python
python:
  - "3.5"

before_install: 
  - mkdir dist
install: 
  - python3 -m pip install setuptools wheel
script: 
  - python3 setup.py sdist bdist_wheel

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "dist/home_temp_sensor-0.0.1-py3-none-any.whl"
  overwrite: true

notifications:
  email: false
