language: python
python:
  - "3.5"
  - "pypy3" 


install:
  - pip install -r requirements.txt
  - pip install .
  
script: pytest

deploy:
  provider: pypi
  user: "__token__"
  password: "$PIPI_TOKEN_PASS" # not the best way but ... not critical to me 

notifications:
  email: false
